git:
  repo: 'mongodb/docs-ruby'
  remote:
    upstream: 'mongodb/docs-ruby'
    tools: 'mongodb/docs-tools'
project:
  name: 'ruby-driver'
  tag: 'ruby-driver'
  url: 'https://docs.mongodb.com/ruby-driver'
  title: 'Ruby Driver Manual'
  branched: true
version:
  release: '2.2'
  branch: '2.2'
system:
  runstate:
    serial_sphinx: publish
  files:
    - 'intersphinx.yaml'
    - 'integration.yaml'
    - 'sphinx_local.yaml'
    - 'push.yaml'
    - htaccess: ['htaccess.yaml']
    - migrations: 
       - 'migrations-bson.yaml'
       - 'migrations-mongoid.yaml'
       - 'migrations-ruby.yaml'
assets:
  - branch: master
    path: build/docs-tools
    repository: https://github.com/mongodb/docs-tools.git
  - branch: 2.2-stable
    path: build/ruby-driver-2.2
    repository: https://github.com/mongodb/mongo-ruby-driver.git
  - branch: master
    path: build/bson-ruby
    repository: https://github.com/mongodb/bson-ruby.git
  - branch: 5.1.0-stable
    path: build/mongoid-5.1
    repository: https://github.com/mongodb/mongoid.git
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
  locale: 'locale'

...