git:
  repo: 'mongodb/docs-ruby'
  remote:
    upstream: 'mongodb/docs-ruby'
    tools: 'mongodb/docs-tools'
project:
  name: 'ruby-driver'
  tag: 'ruby-driver'
  url: 'https://docs.mongodb.com'
  title: 'Ruby Driver Manual'
  branched: true
version:
  release: '1.x'
  branch: '1.x'
system:
  runstate:
    serial_sphinx: publish
  files:
    - 'intersphinx.yaml'
    - 'integration.yaml'
    - 'sphinx_local.yaml'
    - 'push.yaml'
    - migrations: 
       - 'migrations-ruby.yaml'
assets:
  - branch: master
    path: build/docs-tools
    repository: https://github.com/mongodb/docs-tools.git
  - branch: 1.x-stable
    path: build/ruby-driver-1.x
    repository: https://github.com/mongodb/mongo-ruby-driver.git
paths:
  output: 'build'
  source: 'source-v1.x'
  includes: 'source-v1.x/includes'
  images: 'source-v1.x/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
  locale: 'locale'
...