# Each YAML document has the following schema:
#
# from: "the path to the redirected URL"
# to: "the path to the new location for the resource"
# type: "currently this script only supports 'redirect', and
#        ignores all documents with another type."
# code: "the HTTP redirect code. Raises exception if not 301, 302, 303."
# outputs: "a list of branches/paths as follows:"
#
# - 'all': generates redirects for all published branches, but *not* 'manual'. But giza will take care of manual as part of integration.yaml logic in redirects.py
#
# - '<branch>': generates redirects for a specific branch.
#
# - 'before-<branch>': generates redirects for all branches that
#   reflect releases previous to the specified branch. (Inclusive.)
#
# - 'after-<branch>': generates redirects for all branches that
#   reflect releases after the specified branch. (Non-inclusive.)
#
# All paths are relative to the ``source/`` directory.
#
########################################################################
### Giza requires this file, even if no redirects
### More as a safety -- in case, we remove redirects during deploys

from: '/aggregation-framework'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1'
---
from: '/examples'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1'
---
from: '/replica-sets'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1'
---
from: '/read-preference'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1'
---
from: '/write-concern'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1'
---
from: '/bulk-write-operations'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1'
---
from: '/authentication-examples'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1'
---
from: '/gridfs'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1'
---
from: '/tailable-cursors'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1'
---
from: '/web-examples'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1'
---
from: '/faq'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1'
---
from: '/style-guide'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1'
---
from: '/credits'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.1'
---
from: '/bson'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.1'
---
from: '/tutorial/ruby-mongoid-tutorial'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
---
from: '/reference/driver-compatibility'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.1'
---
from: '/reference/additional-resources'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.1'
...
