source:  build/bson-ruby/docs/bson-tutorials.txt
target:  bson-tutorials.txt
---
source:  build/bson-ruby/docs/tutorials/bson-v3.txt
target:  tutorials/bson-v3.txt
---
source:  build/bson-ruby/docs/tutorials/bson-v4.txt
target:  tutorials/bson-v4.txt
...
