source:  build/ruby-driver-2.0/docs/contribute.txt
target:  contribute.txt
---
source:  build/ruby-driver-2.0/docs/index.txt
target:  index.txt
---
source:  build/ruby-driver-2.0/docs/quick-start.txt
target:  quick-start.txt
---
source:  build/ruby-driver-2.0/docs/includes/older-server-versions-unsupported.rst
target:  includes/older-server-versions-unsupported.rst
---
source:  build/ruby-driver-2.0/docs/includes/ruby-driver-compatibility-full-language.rst
target:  includes/ruby-driver-compatibility-full-language.rst
---
source:  build/ruby-driver-2.0/docs/includes/ruby-driver-compatibility-full-mongodb.rst
target:  includes/ruby-driver-compatibility-full-mongodb.rst
---
source:  build/ruby-driver-2.0/docs/includes/ruby-driver-compatibility-matrix-language.rst
target:  includes/ruby-driver-compatibility-matrix-language.rst
---
source:  build/ruby-driver-2.0/docs/includes/ruby-driver-compatibility-matrix-mongodb.rst
target:  includes/ruby-driver-compatibility-matrix-mongodb.rst
---
source:  build/ruby-driver-2.0/docs/includes/unicode-checkmark.rst
target:  includes/unicode-checkmark.rst
---
source:  build/ruby-driver-2.0/docs/reference/additional-resources.txt
target:  reference/additional-resources.txt
---
source:  build/ruby-driver-2.0/docs/reference/driver-compatibility.txt
target:  reference/driver-compatibility.txt
...
