source:  build/ruby-driver/docs/contribute.txt
target:  contribute.txt
---
source:  build/ruby-driver/docs/index.txt
target:  index.txt
---
source:  build/ruby-driver/docs/installation.txt
target:  installation.txt
---
source:  build/ruby-driver/docs/quick-start.txt
target:  quick-start.txt
---
source:  build/ruby-driver/docs/ruby-driver-tutorials.txt
target:  ruby-driver-tutorials.txt
---
source:  build/ruby-driver/docs/tutorials/ruby-driver-admin-tasks.txt
target:  tutorials/ruby-driver-admin-tasks.txt
---
source:  build/ruby-driver/docs/tutorials/ruby-driver-aggregation.txt
target:  tutorials/ruby-driver-aggregation.txt
---
source:  build/ruby-driver/docs/tutorials/ruby-driver-bulk-operations.txt
target:  tutorials/ruby-driver-bulk-operations.txt
---
source:  build/ruby-driver/docs/tutorials/ruby-driver-collection-tasks.txt
target:  tutorials/ruby-driver-collection-tasks.txt
---
source:  build/ruby-driver/docs/tutorials/ruby-driver-create-client.txt
target:  tutorials/ruby-driver-create-client.txt
---
source:  build/ruby-driver/docs/tutorials/ruby-driver-crud-operations.txt
target:  tutorials/ruby-driver-crud-operations.txt
---
source:  build/ruby-driver/docs/tutorials/ruby-driver-geospatial-search.txt
target:  tutorials/ruby-driver-geospatial-search.txt
---
source:  build/ruby-driver/docs/tutorials/ruby-driver-gridfs.txt
target:  tutorials/ruby-driver-gridfs.txt
---
source:  build/ruby-driver/docs/tutorials/ruby-driver-indexing.txt
target:  tutorials/ruby-driver-indexing.txt
---
source:  build/ruby-driver/docs/tutorials/ruby-driver-projections.txt
target:  tutorials/ruby-driver-projections.txt
---
source:  build/ruby-driver/docs/tutorials/ruby-driver-text-search.txt
target:  tutorials/ruby-driver-text-search.txt
---
source:  build/ruby-driver/docs/includes/older-server-versions-unsupported.rst
target:  includes/older-server-versions-unsupported.rst
---
source:  build/ruby-driver/docs/includes/ruby-driver-compatibility-full-language.rst
target:  includes/ruby-driver-compatibility-full-language.rst
---
source:  build/ruby-driver/docs/includes/ruby-driver-compatibility-full-mongodb.rst
target:  includes/ruby-driver-compatibility-full-mongodb.rst
---
source:  build/ruby-driver/docs/includes/ruby-driver-compatibility-matrix-language.rst
target:  includes/ruby-driver-compatibility-matrix-language.rst
---
source:  build/ruby-driver/docs/includes/ruby-driver-compatibility-matrix-mongodb.rst
target:  includes/ruby-driver-compatibility-matrix-mongodb.rst
---
source:  build/ruby-driver/docs/includes/unicode-checkmark.rst
target:  includes/unicode-checkmark.rst
---
source:  build/ruby-driver/docs/reference/additional-resources.txt
target:  reference/additional-resources.txt
---
source:  build/ruby-driver/docs/reference/driver-compatibility.txt
target:  reference/driver-compatibility.txt
...
