source:  build/mongoid-5.1/docs/mongoid-tutorials.txt
target: mongoid-tutorials-5.1.txt
transform: 
  regex: "/tutorials/version/"
  replace: "/tutorials/5.1.0/"
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-callbacks.txt
target: /tutorials/5.1.0/mongoid-callbacks.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-installation.txt
target: /tutorials/5.1.0/mongoid-installation.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-queries.txt
target: /tutorials/5.1.0/mongoid-queries.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-upgrade.txt
target: /tutorials/5.1.0/mongoid-upgrade.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-documents.txt
target: /tutorials/5.1.0/mongoid-documents.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-nested-attributes.txt
target: /tutorials/5.1.0/mongoid-nested-attributes.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-rails.txt
target: /tutorials/5.1.0/mongoid-rails.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-validation.txt
target: /tutorials/5.1.0/mongoid-validation.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-indexes.txt
target: /tutorials/5.1.0/mongoid-indexes.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-persistence.txt
target: /tutorials/5.1.0/mongoid-persistence.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-relations.txt
target: /tutorials/5.1.0/mongoid-relations.txt
...
