source:  build/mongoid-5.1/docs/mongoid-tutorials.txt
target: mongoid-tutorials.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-callbacks.txt
target: tutorials/mongoid-callbacks.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-installation.txt
target: /tutorials/mongoid-installation.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-queries.txt
target: /tutorials/mongoid-queries.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-upgrade.txt
target: /tutorials/mongoid-upgrade.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-documents.txt
target: /tutorials/mongoid-documents.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-nested-attributes.txt
target: /tutorials/mongoid-nested-attributes.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-rails.txt
target: /tutorials/mongoid-rails.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-validation.txt
target: /tutorials/mongoid-validation.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-indexes.txt
target: /tutorials/mongoid-indexes.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-persistence.txt
target: /tutorials/mongoid-persistence.txt
---
source:  build/mongoid-5.1/docs/tutorials/mongoid-relations.txt
target: /tutorials/mongoid-relations.txt
...
